kind: pipeline
name: default

steps:
- name:build:
  image: docker
  environment:
    DOCKER_PASS:
      from_secret: docker_pass
  commands:
  - docker login -u alexeldeib -p $DOCKER_PASS
  - docker build . -t alexeldeib/prometheus-app-insights-write
  - docker push -t alexeldeib/prometheus-app-insights-write
  volumes:
  - name: docker
    path: /var/run/docker.sock
    
volumes:
- name: docker
  host:
    path: /var/run/docker.sock
