apiVersion: apps/v1beta2
kind: Deployment
metadata:
  name: {{ template "prometheus-appinsights-remote-write.fullname" . }}
  labels:
    app: {{ template "prometheus-appinsights-remote-write.name" . }}
    chart: {{ template "prometheus-appinsights-remote-write.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: {{ template "prometheus-appinsights-remote-write.name" . }}
      release: {{ .Release.Name }}
  template:
    metadata:
      labels:
        app: {{ template "prometheus-appinsights-remote-write.name" . }}
        release: {{ .Release.Name }}
    spec:
      containers:
        - name: {{ .Chart.Name }}
          args: ["--ikey", "{{ required "Please provide an instrumentation key to send telemetry to Application Insights." .Values.ikey }}"]
          ports:
           - containerPort: 1234
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          resources:
{{ toYaml .Values.resources | indent 12 }}
    {{- with .Values.nodeSelector }}
      nodeSelector:
{{ toYaml . | indent 8 }}
    {{- end }}
    {{- with .Values.affinity }}
      affinity:
{{ toYaml . | indent 8 }}
    {{- end }}
    {{- with .Values.tolerations }}
      tolerations:
{{ toYaml . | indent 8 }}
    {{- end }}
