apiVersion: v1
kind: Service
metadata:
  name: {{ template "prometheus-appinsights-remote-write.name" . }}
spec:
  ports:
  - port: {{ .Values.service.port }}
    targetPort: 1234
    protocol: TCP
  selector:
    app: {{ template "prometheus-appinsights-remote-write.name" . }}