version: 2
jobs:
  build:
    machine: true
    steps:
      - checkout
      - run: docker login -u $docker_username -p $docker_password
      - run: docker build -t alexeldeib/prometheus-appinsights-remote-write .
      - run: docker push alexeldeib/prometheus-appinsights-remote-write
